        </div>

        <div class="oneThird">
<?php
	include("news.inc");
?>
          <div class="more"><a href="./news.php">More News &raquo;</a></div>

          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>
      </div>
<!---
      <div class="rowOfBoxes dividingBorderAbove">
        <div class="quarter noBorderOnLeft">
          <h1>Standards</h1>
          <p><span lang="la">Prosimii</span> is 100% compliant with
             <acronym title="eXtensible HyperText Markup Language">XHTML</acronym> 1.0 Strict and
             uses <acronym title="Cascading Style Sheets">CSS</acronym>.
             <span class="doNotPrint">[Validate
             <a href="http://validator.w3.org/check/referer">XHTML</a>]</span></p>

          <p>Unlike this design&rsquo;s inspiration, no tables have been used to layout elements
            and text.</p>
        </div>

        <div class="quarter">
          <h1>Stylesheet</h1>
          <p>An external stylesheet dictates the format and layout of text in this design.</p>

          <p>Thus, website-wide design changes can be achieved by editing only the stylesheet.</p>

          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>

        <div class="quarter">
          <h1>Compatibility</h1>
          <p><span lang="la">Prosimii&rsquo;s</span> stylesheet is more robust and comprehensive than
             <a href="http://www.oswd.org/userinfo.phtml?user=haran">my previous designs</a>.</p>

          <p>This design has been tested for consistent rendering in Gecko
             (<a href="http://www.mozilla.org">Mozilla</a> <a href="http://www.getfirefox.com">Firefox</a>
             0.10.1), <a href="http://www.opera.com">Opera</a> (7.01) and Internet Explorer (6.0).</p>
        </div>

        <div class="quarter">
          <h1>Accessibility</h1>
          <p><span lang="la">Prosimii</span> tentatively conforms to the
             <a href="http://www.w3.org/TR/WCAG10">
             <acronym title="Web Content Accessibility Guidelines">WCAG</acronym> double A rating</a>
             and <a href="http://www.access-board.gov/508.htm">&sect;&nbsp;508</a> guidelines for web
             content accessibility.</p>

          <p>Additionally, most document metrics (lengths, widths and spacings) are font-size
             relative.</p>
        </div>
      </div>
    </div>
-->
    <!-- ##### Footer ##### -->

    <div id="footer">
      <span class="doNotPrint">
        For comments or questions about this website, please
        <a href="mailto:uwe@steinmann.cx" title="Webmasters email address">email the Webmaster</a><br />
      </span>

      <strong>URI &raquo;</strong> http://pxlib.sourceforge.net
      &bull; <strong>Updated &raquo;</strong> 2004-Oct-24 10:31 +1000
    </div>
  </body>
</html>
