        </div>

        <div class="oneThird">
<?php
	include("news.inc");
?>
          <div class="more"><a href="./news.php">More News &raquo;</a></div>

          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>
      </div>
    </div>
    <!-- ##### Footer ##### -->

    <div id="footer">
      <span class="doNotPrint">
        For comments or questions about this website, please
        <a href="mailto:uwe@steinmann.cx" title="Webmasters email address">email the Webmaster</a><br />
      </span>

      <strong>URI &raquo;</strong> http://pxlib.sourceforge.net
      &bull; <strong>Updated &raquo;</strong> 2004-Oct-24 10:31 +1000
    </div>
  </body>
</html>
