<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-AU">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="author" content="haran" />
    <meta name="generator" content="haran" />

    <link rel="stylesheet" type="text/css" href="./prosimii-screen.css" media="screen, tv, projection" title="Default" />
    <link rel="stylesheet alternative" type="text/css" href="./prosimii-print.css" media="screen" title="Print Preview" />
    <link rel="stylesheet" type="text/css" href="./prosimii-print.css" media="print" />

    <title>pxlib</title>
  </head>

  <body>
    <!-- For non-visual user agents: -->
      <div id="top"><a href="#main-copy" class="doNotDisplay doNotPrint">Skip to main content.</a></div>

    <!-- ##### Header ##### -->

    <div id="header">
      <div class="superHeader">
        <span>Related Sites:</span>
        <a href="http://www.oswd.org" title="The host of this design">OSWD</a> |
        <a href="http://www.oswd.org/userinfo.phtml?user=haran" title="Other designs by haran">haran&rsquo;s Designs</a>
      </div>

      <div class="midHeader">
        <h1 class="headerTitle" lang="la">pxlib</h1>
        <div class="headerSubTitle" title="Short description of pxlib">
          { Library to read and write Paradox databases }
        </div>

        <br class="doNotDisplay doNotPrint" />

        <div class="headerLinks">
          <span class="doNotDisplay">Tools:</span>
          <a href="./index2.html">view an alternative layout &laquo;</a>
          <span class="doNotDisplay">|</span>
          <a style="cursor: help;" title="Thanks to CSS, this page is already printer friendly!">printer-friendly version &laquo;</a>
        </div>
      </div>

      <div class="subHeader">
        <span class="doNotDisplay">Navigation:</span>
        <a href="./index.php">Home</a> |
        <a href="./documentation.php">Documentation</a> |
        <a href="./installation.php">Installation</a> |
        <a href="http://sourceforge.net/projects/pxlib/">Download</a> |
        <a href="./contact.php">Contact</a>
      </div>
    </div>

    <!-- ##### Main Copy ##### -->

    <div id="main-copy">
      <div class="rowOfBoxes">
        <div class="twoThirds noBorderOnLeft">

