          <h1>Latest News</h1>
					<a href="./index.html" class="newsHeading">Released version 0.5.0</a>
					<p class="newsDate">July 14, 2005</p>
					<p class="newsSummary">
						<ul>
							<li>support for encrypted databases and blob files</li>
					 </ul>
					</p>

  				<a href="./index.html" class="newsHeading">New web site</a>
					<p class="newsDate">02 Feb 05</p>
					<p class="newsSummary">
					  After a long time the web site has been overhauled with much
						more information about pxlib.
					</p>


